CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(30) NOT NULL,
  "code" varchar(5) UNIQUE,
  "email" varchar(50) NOT NULL,
  "password" varchar(15) NOT NULL,
  "age" int NOT NULL
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) NOT NULL
);

CREATE TABLE "videos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "url" varchar(120) NOT NULL
);

CREATE TABLE "courses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(30) NOT NULL,
  "description" varchar(50) NOT NULL,
  "level" varchar(20) NOT NULL,
  "teacher_id" int NOT NULL,
  "video" varchar(20) NOT NULL
);

CREATE TABLE "categories_courses" (
  "category_id" int NOT NULL,
  "course_id" int NOT NULL
);

CREATE TABLE "roles" (
  "rol_id" int PRIMARY KEY NOT NULL,
  "type" varchar(10) NOT NULL
);

CREATE TABLE "videos_courses" (
  "video_id" int UNIQUE NOT NULL,
  "title" varchar(20) NOT NULL,
  "url" varchar(120) NOT NULL,
  "course_id" int NOT NULL
);

ALTER TABLE "courses" ADD FOREIGN KEY ("teacher_id") REFERENCES "users" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "categories_courses" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id");

ALTER TABLE "videos_courses" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id");

ALTER TABLE "videos_courses" ADD FOREIGN KEY ("video_id") REFERENCES "videos" ("id");

ALTER TABLE "roles" ADD FOREIGN KEY ("rol_id") REFERENCES "users" ("id");

-- // LINEAS INSERTADAS EN EL SQL SHELL => CREACION DE REGISTROS//

INSERT INTO users (name, code, email, password, age) VALUES ('NICOLAS', '456', 'nicolas@gmail.com', '123456789', '30');
INSERT INTO users (name, code, email, password, age) VALUES ('MARIA', '123', 'majes@gmail.com', '987654321', '26');

INSERT INTO categories (name) VALUES ('Marketing'), ('Design'), ('Bussiness'), ('IT & Software');

INSERT INTO videos (title, url) VALUES ('Complete Python Bootcamp', 'https://www.udemy.com/course/complete-python-bootcamp/'), 
('CSS & JavaScript', 'https://www.udemy.com/course/css-javascript-certification-course-for-beginners/'),
('Complete Communication Skills', 'https://www.udemy.com/course/the-complete-communication-skills-master-class-for-life/');


INSERT INTO courses (title, description, level, teacher_id, video) VALUES ('Communications Mng', 'Skills for Persuasion ´n Business Communication', 'Beginners', 123, 'Communicationskills'),
('Javascript4Beginners', 'Learn javascript online and supercharge your web', 'Beginners', 123, 'JavaScript begginers'),
('Kids Coding HTML and CSS!', 'Your kid could be the next Zuckerberg!', 'Beginners', 123, 'Introduction to html');

INSERT INTO roles (rol_id, type) VALUES (1, 'student'), (2, 'teacher'), (3, 'admin');